#!/usr/bin/env bash
# slothcv — local dev server starter (macOS / Linux).
# Fresh-clone-safe: verifies node, installs deps if missing, frees
# port 3000, clears framework cache, starts dev server, waits for
# the port to listen, opens browser.
#
# @generated-by:apply_portable_dev_scripts.py
# Auto-generated by scripts/apply_portable_dev_scripts.py — don't
# hand-edit unless you also update the generator (the marker above
# tells the generator it's safe to refresh; remove it to lock the
# file against future regeneration).
#
# Prereqs: Node 18.18+ and bun in PATH. Get Node at nodejs.org
# Usage: chmod +x start_local_server.sh && ./start_local_server.sh

set -euo pipefail

PORT=3000
MANAGER=bun
NAME="slothcv"

# Set CWD to the script's folder regardless of where it was invoked.
cd "$(dirname "$0")"

# 1. Verify node + manager are available.
if ! command -v node >/dev/null 2>&1; then
    echo "[ERROR] Node.js not found in PATH."
    echo "Install Node 18.18 or newer from https://nodejs.org"
    exit 1
fi
if ! command -v "$MANAGER" >/dev/null 2>&1; then
    echo "[ERROR] $MANAGER not found in PATH."
    echo "Install Bun from https://bun.sh (curl one-liner on Mac/Linux, PowerShell on Windows)."
    exit 1
fi

# 2. Install deps if node_modules is missing (fresh-clone case).
if [ ! -d "node_modules" ]; then
    echo "[setup] node_modules missing — running $MANAGER install..."
    "$MANAGER" install
fi

# 3. Free port.
echo "[setup] Freeing port $PORT..."
if command -v lsof >/dev/null 2>&1; then
    PIDS=$(lsof -ti tcp:$PORT 2>/dev/null || true)
    if [ -n "$PIDS" ]; then
        kill -9 $PIDS 2>/dev/null || true
    fi
elif command -v fuser >/dev/null 2>&1; then
    fuser -k "${PORT}/tcp" >/dev/null 2>&1 || true
fi

# 4. Clear framework dev cache.
[ -d ".next/dev" ] && rm -rf .next/dev

# 5. Start dev server in background; Ctrl+C will kill it via trap below.
echo "[setup] Starting $NAME dev server on http://localhost:$PORT..."
"$MANAGER" run dev &
DEV_PID=$!

# Trap Ctrl+C / TERM so the child server gets killed when this script exits.
trap 'kill $DEV_PID 2>/dev/null || true; exit 0' INT TERM

# 6. Wait until port accepts connections (max ~60s), then open browser.
echo "[setup] Waiting for server to come up..."
tries=0
while [ $tries -lt 60 ]; do
    if command -v nc >/dev/null 2>&1; then
        if nc -z localhost $PORT 2>/dev/null; then break; fi
    elif command -v curl >/dev/null 2>&1; then
        if curl -s -o /dev/null --max-time 1 "http://localhost:$PORT"; then break; fi
    else
        sleep 3
        break
    fi
    sleep 1
    tries=$((tries + 1))
done

URL="http://localhost:$PORT"
if command -v open >/dev/null 2>&1; then
    open "$URL"            # macOS
elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$URL"        # Linux
elif command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "$URL"  # WSL on Windows
else
    echo "[setup] Open $URL in your browser."
fi

# Keep the script attached to the dev server so Ctrl+C stops it cleanly.
wait $DEV_PID
