"""
Full Tier-1 conversion: in every bespoke template, replace
`{<itemvar>.<field> || "<Label>"}` patterns with proper
<EditableFallback> wrapping so each individual field becomes a
double-clickable inline-edit target with the canonical italic-gray
placeholder treatment.

Replacement assumes `data` and a section-id reference are in scope.
Most bespoke templates pass `section` (the Section object) and
`data` (the full ResumeData) into their item-mapping functions, so
the generated `fieldId` reads
  `section.${section.id}.item.${<itemvar>.id}.<field>`
which the existing element-text-lens picks up via its
`section.<sid>.item.<iid>.<field>` route — the lens already supports
EVERY inner-field name without changes.

Idempotent: skips occurrences already wrapped with
<EditableFallback>. Safe to re-run.

Failure handling: if a template uses a renamed section variable (e.g.
the function destructures as `{ section: s }` so `section` isn't in
scope), the substitution will TypeScript-fail in build. The script
records a warning so we can hand-fix those.
"""

from __future__ import annotations
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "src" / "templates"

# Templates already converted (Aurora's done by hand; the shared
# components.tsx covers the templates that route through SectionBody).
SKIP_FILES = {
    "components.tsx", "frame.tsx", "renderer.tsx", "section-actions.tsx",
    "shared.ts", "registry.ts", "custom-elements-layer.tsx", "blank.tsx",
    "aurora.tsx",  # full EditableFallback already applied by hand
}

USES_SHARED_SECTION_BODY = {
    "atlas.tsx", "bento.tsx", "berlin.tsx", "capitol.tsx", "copenhagen.tsx",
    "dashboard.tsx", "dubai.tsx", "frankfurt.tsx", "geneva.tsx",
    "heidelberg.tsx", "helsinki.tsx", "madrid.tsx", "manhattan.tsx",
    "marina.tsx", "mosaic.tsx", "notion.tsx", "oslo.tsx", "reykjavik.tsx",
    "scratch.tsx", "singapore.tsx", "tokyo.tsx", "vesterbro.tsx",
    "vienna.tsx", "zurich.tsx",
}

# Item-iteration variable names commonly used in templates.
ITEM_VARS = ["it", "c", "a", "p", "t", "r", "l", "s", "b", "h", "ref"]

# Pattern: `{<itemvar>.<field> || "<Label>"}` — a JSX expression with
# a fallback string. Generated by the previous add-fallback-placeholders
# pass. We capture the item var, field name, and label so the
# replacement can stamp them into <EditableFallback>.
PATTERN = re.compile(
    r'\{('
    + "|".join(ITEM_VARS)
    + r')\.([a-zA-Z]+) \|\| "([^"]+)"\}'
)


def process(content: str) -> tuple[str, int]:
    count = 0

    def repl(m: re.Match) -> str:
        nonlocal count
        var = m.group(1)
        field = m.group(2)
        label = m.group(3)
        count += 1
        return (
            f'<EditableFallback data={{data}} fieldId={{`section.${{section.id}}.item.${{{var}.id}}.{field}`}} '
            f'value={{{var}.{field}}} placeholder="{label}" />'
        )

    return PATTERN.sub(repl, content), count


def ensure_import(content: str) -> str:
    """Ensure EditableFallback is imported from ./components."""
    if re.search(r'import\s*\{[^}]*EditableFallback[^}]*\}', content):
        return content
    pat = re.compile(r'^import\s*\{([^}]*)\}\s*from\s*"\./components";', re.MULTILINE)
    m = pat.search(content)
    if m:
        existing = [s.strip() for s in m.group(1).split(",") if s.strip()]
        if "EditableFallback" not in existing:
            existing.append("EditableFallback")
        new_import = (
            'import { ' + ", ".join(sorted(set(existing))) + ' } from "./components";'
        )
        return content[:m.start()] + new_import + content[m.end():]
    # No existing components import — splice one in after the last top-level import.
    import_pat = re.compile(r'^(import\s+[^;]+;)$', re.MULTILINE)
    last = None
    for hit in import_pat.finditer(content):
        last = hit
    if last is None:
        return content
    insertion = '\nimport { EditableFallback } from "./components";'
    return content[:last.end()] + insertion + content[last.end():]


def main() -> int:
    changed = []
    for fname in sorted(os.listdir(TEMPLATES)):
        path = TEMPLATES / fname
        if not path.is_file() or not fname.endswith(".tsx"):
            continue
        if fname in SKIP_FILES or fname in USES_SHARED_SECTION_BODY:
            continue
        text = path.read_text(encoding="utf-8")
        new, n = process(text)
        if n == 0:
            continue
        new = ensure_import(new)
        path.write_text(new, encoding="utf-8")
        changed.append((fname, n))
    print(f"Updated: {len(changed)}")
    for f, n in changed:
        print(f"  - {f}: {n} field(s) wrapped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
